{{- if .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "synctv.fullname" . }}-headless
  labels:
    {{- include "synctv.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "synctv.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.config.server.grpcPort }}
      targetPort: grpc
      protocol: TCP
{{- end }}
