apiVersion: v1
kind: Service
metadata:
  name: {{ include "synctv.fullname" . }}
  labels:
    {{- include "synctv.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerIP }}
  {{- if ne . "" }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.config.server.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.config.server.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.config.livestream.rtmpPort }}
      targetPort: rtmp
      protocol: TCP
      name: rtmp
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePorts.rtmp }}
      nodePort: {{ .Values.service.nodePorts.rtmp }}
      {{- end }}
    {{- if .Values.config.webrtc.enableBuiltinStun }}
    - port: {{ .Values.config.webrtc.stunPort }}
      targetPort: stun
      protocol: UDP
      name: stun
    {{- end }}
  selector:
    {{- include "synctv.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
