apiVersion: v1
kind: Service
metadata:
  name: {{ include "synctv.fullname" . }}
  labels:
    {{- include "synctv.labels" . | nindent 4 }}
  {{- $annotations := dict }}
  {{- if .Values.metrics.enabled }}
  {{- $_ := set $annotations "prometheus.io/scrape" "true" }}
  {{- $_ := set $annotations "prometheus.io/port" (.Values.metrics.port | default .Values.config.server.httpPort | toString) }}
  {{- $_ := set $annotations "prometheus.io/path" (.Values.metrics.path | default "/metrics") }}
  {{- end }}
  {{- with .Values.service.annotations }}
  {{- range $k, $v := . }}
  {{- $_ := set $annotations $k $v }}
  {{- end }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- range $k, $v := $annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerIP }}
  {{- if ne . "" }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.config.server.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.config.server.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.config.livestream.rtmpPort }}
      targetPort: rtmp
      protocol: TCP
      name: rtmp
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePorts.rtmp }}
      nodePort: {{ .Values.service.nodePorts.rtmp }}
      {{- end }}
    {{- if .Values.config.webrtc.enableBuiltinStun }}
    - port: {{ .Values.config.webrtc.stunPort }}
      targetPort: stun
      protocol: UDP
      name: stun
    {{- end }}
  selector:
    {{- include "synctv.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
